# Generated by Django 4.1.5 on 2023-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('quantidade_produto', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
